language: python
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - chmod -w data/read_only.fasta
script:
  - pipenv run tests
after_success:
  - pipenv run codecov
notifications:
  email: false
  slack:
    secure: DNjnMK6hvSnVR+74xr+iKh4rvrz2xXjX9ZRPNW5Xl+8n+BYhy7TokWysm9+vgDrFW6ji/O6VuYutyOhxxx3qvoVlm/77m+Vj/uOnxskWKMhvkXFCvEnmp1lA4O2s3Nqkp75auPlc5twDFl51WzyjC7nJbH8G1yIKwFJhv5yjSuDTGJ7SkJ69IeAiTYJdmXQs7LSPcYgdHdxCNWsGa7/dmPLYwuNegY/rECJqpfrUNx5It/ACx53zihXoF77cEq6/YxnBAVQSagr0SnuO486irMvXgWlEyzvmMLG4FRkuU6KaZtaXiSaBU20qW5ZV9Q1Jk9SFAo9m3zaLNvC9tJEXM66I3bSfKhIsfhikfbQ8oVZPTTbhoDR+M6PhR/uRwg2NbS0r1iTZ/amZQBr3yw0nO7v/ypMwU87DFALL4waZH+PygFzlfXCNGpb89aDgvx4J6GDJp1spA91rQleEX8o4x4O8gO/IqllwEMCa9pbicoFR0xMwCbPitiuwG9QN4xip1CVVPh8rRrt7F5cOLupTBGpDXOQsyBg1XgjqzUMvZehYkgqWi54sQm0Ciw0u+rGIP2Bq9U8JCh4xjknEflrbgunWycSC4IdS/8au0fo6f6ZyT8qWPWVyt4k11Y+KOtqJ3HCU2kCz0dPUuOxLo8xS+Blr0kPlT08n7JOUsIzKWDY=
deploy:
  provider: pypi
  user: hadrieng
  password:
    secure: ZbJQypOrraPFPuTrovJHDMDOGgpTgV+Am/FDQaWT3O8m9WUnM1V140fegsEv4xRRIlTJHsHNj/zOz5s9CRTjHgB2aA4j73FmuV8CNOBrb54uCC5Msd3m6Y8uHvQwdb85eTQYcTcjmzZNVhTITBFssluvV7C6p6MGsJRjCphjx9reai5xIXS4rR47fcxvchBTdXsu7KUwlMQBueIr+zbILjpjosfeU5/CaY6NPzTQKTe/03IZeC2x5lkI/Sp7LAHZUnHNjtm/sV3b/KduAtuJ2T/TCx+j2O13WH9NcBCBhMRIn3i0567/7hkkJbeUFdeZa4YKkh+hMX1ILrFhlpfIDm04Dod2OrCkISTJ2bZvPCfZGL+vnNJQMZXgvAlirN0hkJ1HfWGq0xIqoooP3J2wGmmWYJCe1lVOSnRzCw/K5/jtKsw+1QcSLpbhTKoMRjhXT8qPPmGwnaLOoR9tv4GXb2wkLxS8Ok/0zgjHu8MAP/0L+qlpLPhFxkfA06IYvTbGsxd0y2ldVFln5Zpkzj48qVuQiJcdKm8ClwI3PWrXLOAs23KltuFgRXthRZOeH6+16AeS/cwrLZ9tHy3thxeYoS6G3eImlaX5D1te/iCKXKNyKOIF2/S4kiQk8Od3C+pKoLsmhsoItWx6wE+Uf0trBjXS3iVs+g+uWGmwaLJiSOk=
  on:
    tags: true
  skip_existing: true
  distributions: "sdist bdist_wheel"
